Repository TECoding/hitec-2021, pull requests merged in 2021-07, with the labels that each got.

#3 Improved readme and started the contribution guide.
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/FEATURE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/images/img.png
  .github/images/img_1.png
  .github/images/img_2.png
  .github/images/img_3.png
  .github/images/img_4.png
  .gitignore
  README.md
  frontend/README.md
Labels: documentation

#11 Installation and configuration of routes
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Inicio.jsx
  frontend/src/components/Preguntas.jsx
  frontend/src/components/Resultado.jsx
Labels: enhancement

#20 Started Landing-Page
  frontend/public/logo_fetec.svg
  frontend/public/logo_tecoding.svg
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.scss
  frontend/src/background.svg
  frontend/src/components/Inicio.css
  frontend/src/components/Inicio.jsx
Labels: enhancement

#19 Added title and icon
  frontend/public/index.html
  frontend/public/logo_hitec.svg
Labels: enhancement

#21 Responsive Design
  frontend/public/logo_fetec.svg
  frontend/public/logo_tecoding.svg
  frontend/src/App.css
  frontend/src/background-resp.svg
  frontend/src/background.svg
  frontend/src/components/Inicio.css
Labels: enhancement

#18 Feature/question card
  frontend/src/components/NavigationButtons/NavigationButtons.jsx
  frontend/src/components/QuestionCard/QuestionCard.jsx
  frontend/src/components/QuestionCard/QuestionCard.scss
Labels: P0, enhancement

#23 Result screen added
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Resultado.css
  frontend/src/components/Resultado.jsx
Labels: enhancement

#25 Logo Updates
  frontend/public/logo_fetec.svg
  frontend/public/logo_tecoding.svg
Labels: enhancement

#27 Feature/components integration
  frontend/src/App.css
  frontend/src/components/NavigationButtons/NavigationButtons.jsx
  frontend/src/components/Preguntas.jsx
  frontend/src/components/QuestionCard/QuestionCard.jsx
  frontend/src/components/QuestionCard/QuestionCard.scss
Labels: P0, enhancement

#29 Fixed links
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Inicio.css
  frontend/src/components/Inicio.jsx
  frontend/src/components/Resultado.css
  frontend/src/components/Resultado.jsx
Labels: P3, enhancement

#30 Background changed
  frontend/src/background.svg
Labels: enhancement

#33 Styling/responsiveness
  frontend/package-lock.json
  frontend/src/background.svg
  frontend/src/components/QuestionCard/QuestionCard.jsx
  frontend/src/components/QuestionCard/QuestionCard.scss
Labels: enhancement

#35 Removed Logos when the user starts the test
  frontend/src/App.js
Labels: enhancement

#39 Result Screen completed with Answers data
  frontend/src/components/Inicio.jsx
  frontend/src/components/QuestionCard/QuestionCard.jsx
  frontend/src/components/Resultado.css
  frontend/src/components/Resultado.jsx
  frontend/src/useLocalStorage.js
Labels: P3, enhancement

#44 Added descriptions for every groups
  frontend/src/components/Resultado.jsx
Labels: P0, enhancement
