Repository TECoding/hitec-2021, pull requests merged in 2021-08, with the labels that each got.

#46 Accessing /resultados give undefined RESOLVED
  frontend/src/components/Resultado.css
  frontend/src/components/Resultado.jsx
Labels: bug

#47 Bugfix/Restarting the test keep previous answers RESOLVED
  frontend/src/components/Resultado.jsx
Labels: bug

#45 Fixed blank space in mobile view
  frontend/src/App.css
Labels: P1, bug

#48 Update Category Descriptions
  frontend/src/components/Resultado.jsx
Labels: enhancement
